apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-worker
  name: demo-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-worker
    spec:
      containers:      
      - name: demo-worker
        image: cainelli/demo-worker
        env:
          - name: API_URL
            value: http://demo-master/next
          - name: TASK_TIME
            value: '2000'
        lifecycle:
          preStop:
            exec:
              command: ["/usr/bin/touch", "/stop_worker"]
