kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: demo-worker
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: demo-worker
  minReplicas: 1
  maxReplicas: 30
  metrics:
  - type: Object
    object:
      metricName: demo_focus_queue_size
      targetValue: 1k
      target:
        apiVersion: v1
        kind: Service
        name: demo-master
