apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: demo-master
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: demo-master
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: demo-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-master
subjects:
- kind: ServiceAccount
  name: demo-master
  namespace: default
