apiVersion: v1
kind: Service
metadata:
  name: demo-master
  namespace: default
  labels:
    app: demo-master
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 10080
  selector:
    app: demo-master
