apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-master
  namespace: gygops
  labels:
    team: frontend
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: demo-master
  endpoints:
  - port: http
    interval: 5s
    path: /metrics
